#==================================================
# Script Name : _Remediate.ps1
# Synopsis    : Remediation script for ...
# Description : ...
# Notes       : ...
# Last update : yyyy.mm.dd by Your Name Here ...
#==================================================

# Exit 0 : Remediation was successful
# Exit 1 : Remediation failed
