#==================================================
# Script Name : _Detect.ps1
# Synopsis    : Detection script for ...
# Description : ...
# Notes       : ...
# Last update : yyyy.mm.dd by Your Name Here ...
#==================================================

# Exit 0 : Do not run remediation
# Exit 1 : Run remediation script